### ISSUE TITLE
Logos et descriptions des parrains/mécènes

### ISSUE THREAD

**Issue by yjacolin** [OSGeo-fr/QGIS-conf-fr-website#1]

**Comment by jmarsac** [comment]
![seminaire4-mecene](https://user-images.githubusercontent.com/1390831/32487864-2755c7c2-c3ab-11e7-8bc0-d15d29f8c503.png)
![seminaire4-parrain](https://user-images.githubusercontent.com/1390831/32487875-2c531748-c3ab-11e7-8ba1-be32b6070081.png)
Voici les deux logos mécène et parrain

**Comment by yjacolin** [comment]
Merci mais ce n'est pas ce qui été demandé, on parle des logos de c2c, 3liz, etc. :)

**Comment by haubourg** [comment]
et hop:
![oslandia_logo](https://user-images.githubusercontent.com/1629853/32491094-b39abb34-c3b5-11e7-897a-1bb60ea8abcf.png)

**Comment by ThomasG77** [comment]
Pour le logo me concernant, la description viendra bientôt
![logo_webgeodatavore_900x900](https://user-images.githubusercontent.com/642120/32525254-d600206a-c423-11e7-8e14-81d16ae5021b.png)

**Comment by ThomasG77** [comment]
Pour la description, j'ai fait une PR. Cf #2

**Comment by yjacolin** [comment]
ping @rldhont et @haubourg une description en tant que parrain et mécène ? PR ou texte en commentaire du ticket welcome  :) ca se passe ici : https://github.com/OSGeo-fr/QGIS-conf-fr-website/blob/master/z30_parrainnages.md
