### ISSUE TITLE
Publication actu 2023

### ISSUE THREAD

**Issue by mfangain** [OSGeo-fr/QGIS-conf-fr-website#103]
J'ai créé une nouvelle branche pour créer une nouvelle actu, mais je ne sais pas comment "merger" et appliquer ma modif...
J'aurais peut-être dû le faire directement dans la branche master?
Désolée, je tâtonne un peu avec le système... :)

**Comment by DelazJ** [comment]
@mfangain Tu vas sur ta branche (sélectionnable depuis la liste déroulante master), tu cliques sur le bouton "Contribute" tout à droite, et dans la liste déroulante sélectionne "Open pull request"

**Comment by DelazJ** [comment]
>  J'aurais peut-être dû le faire directement dans la branche master?

Oui, si la modif est triviale et n'appelle pas à discussion.
>  Désolée, je tâtonne un peu avec le système... :)

Encore heureux! C'est rassurant On y a tous eu droit, pourquoi pas toi?  😄

**Comment by mfangain** [comment]
Les créations d'actus, je sais pas si ça appelle à discussion ?

**Comment by mfangain** [comment]
Mon actu n'apparait toujours pas sur le site, il manque une étape, un élément quelque part?

**Comment by DelazJ** [comment]
@mfangain Voyons voir ce que fait https://github.com/OSGeo-fr/QGIS-conf-fr-website/commit/df9e529d1942908a320d4947bdc28282b312d9d7

**Comment by DelazJ** [comment]
C'est bon. Je pense que c'est peut-être parce qu'il manquait l'extension du fichier

**Comment by mfangain** [comment]
ah oui, ok. Je note pour la prochaine fois. Merci @DelazJ :)
