### ISSUE TITLE
Prolongation appel à propositions

### ISSUE THREAD

**Issue by mfangain** [OSGeo-fr/QGIS-conf-fr-website#108]
Salut!
J'ai créé un nouveau post pour les actus du site des conférences.
A priori, il faut une revue, je ne sais pas de qui, et je ne sais pas si vous avez reçu des notifications...
(je suis pas encore tout à fait au point avec le site ;-))
Marjorie

PS : je viens de voir que Harrissou a aussi bossé dessus... On en parle tout à l'heure.

**Comment by DelazJ** [comment]
J'ai retiré le post que j'avais écrit, le tien étant nettement plus vendeur. Le reste c'est pour ajuster les dates afin d'afficher la même partout.
et oui, quand t'as ouvert la pull request, on a reçu notification. Et la review est faite donc, sauf si tu veux attendre la réunion avant de publier, c'est bueno pour moi.

**Comment by mfangain** [comment]
ok, ça marche! Merci Harrissou!
Ce serait bien qu'on fasse les 2 publications en même temps, et je pourrai lancer après le tweet qui est prêt.

**Comment by DelazJ** [comment]
C'est fait, le site devrait s'actualiser dans les minutes avec les infos

**Comment by mfangain** [comment]
Impeccable, ça fonctionne. Merci encore!
Je lance le tweet qui va avec.
