### ISSUE TITLE
Détail contrepartie sponsor

### ISSUE THREAD

**Issue by SebastienPeillet** [OSGeo-fr/QGIS-conf-fr-website#112]
@mfangain @DelazJ @Bakaniko (et d'autres si besoin est :) )

J'ai une question pour la mise à jour du site. Pour la page parrainage, on a gardé les mêmes contrepartie que les années précédentes en distanciel. Je ne me suis pas posé la question de leur pertinence à ce moment là. Notamment on inclut des places d'ateliers parce que c'était la seule inscription payante en distanciel. Est-ce qu'on garde cela, est-ce qu'on inclut la journée de conférence, ou l'on change l'un pour l'autre, ou on laisse la possibilité de choisir ? Je pose la question car je crois pas qu'on en ait parlé (mais j'ai loupé quelques réunions :clown_face: )

et il faut que je modifie la mention : 

`Maintien du logo et du lien vers l'organisme sur la page du site de l'événement "Nos précédents soutiens"`

Parce que c'est la page archive... `Nos précédents soutiens` elle existe pas ^^

**Comment by mfangain** [comment]
désolée, je suis arrivée un peu tard. Très bien tes modifs @SebastienPeillet  :)
