### ISSUE TITLE
La mise en page sur téléphone / tablette est inconfortable

### ISSUE THREAD

**Issue by haubourg** [OSGeo-fr/QGIS-conf-fr-website#15]
Je teste le thème sur les outils responsive de la console FF: 

![image](https://user-images.githubusercontent.com/1629853/60711928-32aff500-9f16-11e9-8d2b-076ce5f13470.png)

C'est assez peu confortable, mais fonctionnel. A voir si on peut améliorer le template ou si des mises à jour existent sur ce thème pour gérer cela mieux

**Comment by haubourg** [comment]
@sylvainbeo la page d'accueil en mode téléphone tablette mériterait une mise en page un peu plus compacte, le site sera pas mal utilisé pendant la conférence et dans les transport. Tu vois une solution simple et rapide? Si ça demande du temps, on laisse tomber, ce n'est pas très critique.

**Comment by sylvainbeo** [comment]
@haubourg Je regarde et corrige ça au plus vite. Et je ferai une nouvelle PR.

**Comment by sylvainbeo** [comment]
PR en cours.

**Comment by haubourg** [comment]
fixed by #16  Merci @sylvainbeo !

**Comment by sylvainbeo** [comment]
TOP. Je ferme l'issue.
