### ISSUE TITLE
Menu toujours visible ?

### ISSUE THREAD

**Issue by sylvainbeo** [OSGeo-fr/QGIS-conf-fr-website#18]
Tout est dans le titre, est-ce que vous voulez un menu fixe toujours en haut de la page, même quand le contenu est scrollé ?

**Comment by haubourg** [comment]
@sylvainbeo Je suis pour! Il disparait effectivement trop vite quand on scroll

**Comment by sylvainbeo** [comment]
https://github.com/OSGeo-fr/QGIS-conf-fr-website/pull/19
