### ISSUE TITLE
Minimistan

### ISSUE THREAD

**Issue by jmarsac** [OSGeo-fr/QGIS-conf-fr-website#185]
@all La soirée au Minimistan n'apparaît nulle part sur le site, on ne la trouve que sur HelloAsso. Qu'en pensez-vous ?

**Comment by jmarsac** [comment]
@SebastienPeillet @haubourg @DelazJ @mfangain ✋

**Comment by haubourg** [comment]
+1, pas trop le temps ce soir, PSC QGIS de mon coté
