### ISSUE TITLE
Intégrer le fil twitter dans la page d'accueil?

### ISSUE THREAD

**Issue by haubourg** [OSGeo-fr/QGIS-conf-fr-website#20]
Je me demande si intégrer le fil twitter dans la page d'accueil, dans une colonne à droite ne serait pas plus efficace que l'affichage des dernières entrées de posts pour informer des dernières nouvelles. @jmarsac qu'est-ce que tu en penses? 

 @sylvainbeo j'ai essayé de faire l'intégration, sans succès. Tu as déjà fait ça?

**Comment by yjacolin** [comment]
Idem que précédement : tu dois faire un template "frontpage" où tu peux inclure d'autres éléments (ie d'autres pages) ou ajouter du code HTML :)

**Comment by jmarsac** [comment]
Oui. Il se substituerait aux posts d'actualités ou bien ceux-ci perdureraient ?

**Comment by yjacolin** [comment]
Mon opinion : il faut les 2, car ils ont des objectifs différents :
* actualités : informer les personnes qui viennent des dernières infos de l'évent
* Twitter : dynamisme créé autour de l'évent.
