### ISSUE TITLE
Intégration du shop QGIS

### ISSUE THREAD

**Issue by haubourg** [OSGeo-fr/QGIS-conf-fr-website#21]
Je continue dans mes idées saugrenues, je me demande si mettre en avant directement le shop QGIS dans une page dédiée soutien permettrait pas d'avoir plus de gens habillés en QGIS le jour de l'évènement et donc de financer un peu QGIS.org. 

Le shop est là https://shop.spreadshirt.net/qgis/ 
et les instructions là. 
https://help.spreadshirt.com/hc/en-us/articles/207487815-Website-integration-with-JavaScript 

Evidemment j'ai essayé aussi mais je ne maitrise pas encore Jekyll pour insérer proprement du javascript..

**Comment by yjacolin** [comment]
Il faut faire un template html "shop" que tu appelles dans la page. Un exemple : https://gitlab.com/yjacolin/laplagneswing/blob/master/_layouts/localisation.html et https://gitlab.com/yjacolin/laplagneswing/blob/master/localisation.md (sans code JavaScript mais le principe reste le même).

**Comment by jmarsac** [comment]
+1

Jean-Marie

Le 16/07/2019 à 12:35, Régis Haubourg a écrit :

**Comment by haubourg** [comment]
merci @yjacolin pour les tuyaux

**Comment by haubourg** [comment]
Bon ça fonctionne, mais le bandeau de menu est trop chargé de cette manière. Quelqu'un a une idée de mise en page pour améliorer ça? 
![image](https://user-images.githubusercontent.com/1629853/61296901-5c510200-a7db-11e9-89ff-1fd930ec309f.png)

**Comment by haubourg** [comment]
J'ai mis ça sur une branche chez moi:

https://github.com/haubourg/QGIS-conf-fr-website/tree/add_qgis_support_page

**Comment by sylvainbeo** [comment]
Localisation, Contact, Archives et A propos pourrait aller dans un footer ?

**Comment by jmarsac** [comment]
Pour ma part, je mettrais plutôt Contact, Archives, A propos, Goodies dans un footer toujours visible comme le header. Et je rajouterais un lien sur la page Goodies dans la page d'Incription

**Comment by sylvainbeo** [comment]
> Pour ma part, je mettrais plutôt Contact, Archives, A propos, Goodies dans un footer toujours visible comme le header. Et je rajouterais un lien sur la page Goodies dans la page d'Incription

Un header toujours visible, je trouve ça pratique. Pour un footer je suis plus perplexe.

**Comment by jmarsac** [comment]
Je me suis fait la même réflexion après avoir validé; on peut donc oublier le côté toujours visible du footer

**Comment by haubourg** [comment]
@sylvainbeo je veux bien un coup de main pour déplacer les pages contact, archives et à propos dans le footer. 


> Je me suis fait la même réflexion après avoir validé; on peut donc oublier le côté toujours visible du footer

+1 ça se fait pas trop le footer toujours visible

**Comment by sylvainbeo** [comment]
> @sylvainbeo je veux bien un coup de main pour déplacer les pages contact, archives et à propos dans le footer.

Ok je fais une PR

**Comment by sylvainbeo** [comment]
https://github.com/OSGeo-fr/QGIS-conf-fr-website/pull/22
