### ISSUE TITLE
Corriger les alertes de sécurité

### ISSUE THREAD

**Issue by haubourg** [OSGeo-fr/QGIS-conf-fr-website#39]
@SebastienPeillet @sylvainbeo 

Il y a des vulnérabilités remontées par github ici https://github.com/OSGeo-fr/QGIS-conf-fr-website/network/alerts 

Vous savez comment corriger ça? J'ai commencé à modifier le fichier `gem.lock` et j'ai pris peur sur les différences de dépendances sur `kramdown`

**Comment by SebastienPeillet** [comment]
là j'ai une erreur 404, normalement c'est que la page n'existe pas mais j'imagine que c'est une question d'accès (une erreur 403 normalement)

**Comment by haubourg** [comment]
@SebastienPeillet je viens de te passer admin, tu ne vois toujours pas la page ?

**Comment by SebastienPeillet** [comment]
Oui, je jetterai un œil

**Comment by SebastienPeillet** [comment]
corrigé par #40
