### ISSUE TITLE
Pense-bête organisation

### ISSUE THREAD

**Issue by haubourg** [OSGeo-fr/QGIS-conf-fr-website#5]
Suite au calage SupAgro - OSGEO-FR, voilà les actions à garder en tête pour l'an prochain:

Responsable | OS-Geo | SupAgro | A faire
-- | -- | -- | --
Communication | Georezo, Twitter, Confs... | Réseau Agro, TD, Twitter,             blog |  
Budget |   | Prévisionnel et réel | Modifier les budgets: 50 pour les                 deux jours, 30 par jour que ce soit le jeudi ou le                 vendredi seul + bouton "vous voulez soutenir le proje"
Inscriptions |   | Prévisionnel et réel | Rajouter dans le formulaire qu'on                 peut récupérer les attestations le vendredi à l'accueil
Logistique | Prévenir de la logistique Barcam et aider à             l'installation le jour J | Amphi, traiteur,             détails des jours j |  
Programme Conf | Animation processus de             présentations | Recherche et vote | Le responsable prévoit comment se                 fait l'accueil
Soutiens | Prospection | Relai admin et financier | Changer             les formules 200 Soutien -500 Parrain -800 Mécène             --> Termes à valider
Progamme Barcamp | Coupler Barcamp et             formule d'ateliers | Envisager un lien avec les             AgroTIC qui auraient une casquette transfert de compétence | Acter au printemps 2018 si                 modification du BarCamp;                  Améliorer l'accueil (présentation, moment de lancement                 officiel)

**Comment by jmarsac** [comment]
Hello @haubourg,  ok pour fermer ce ticket ?

**Comment by haubourg** [comment]
Of course!
